services:
    tomcat:
        image: retwisj
        depends_on:
            - redis
        ports:
            - "8080:8080"
        networks:
            - "lab"
    redis:
        image: redis:6.0-alpine
        ports:
            - "6379:6379"
        networks:
            - "lab"
networks:
    lab:
        ipam:
            driver: default